title: openSUSE Kubic
name: Kubic
email: opensuse-factory@opensuse.org
description: Project maintaining multiple container-related technologies as part of the openSUSE Project
baseurl: ""
url: ""
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 7
paginate_path: "/blog/page:num/"
