title: openSUSE Kubic
email: opensuse-factory@opensuse.org
description: >-
  Providing the openSUSE MicroOS Container Operating System and the Kubic
  Container as a Service Platform based on MicroOS and kubernetes
baseurl: ""
url: ""
